require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DailyTasksController do

  # This should return the minimal set of attributes required to create a valid
  # DailyTask. As you add validations to DailyTask, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DailyTasksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all daily_tasks as @daily_tasks" do
      daily_task = DailyTask.create! valid_attributes
      get :index, {}, valid_session
      assigns(:daily_tasks).should eq([daily_task])
    end
  end

  describe "GET show" do
    it "assigns the requested daily_task as @daily_task" do
      daily_task = DailyTask.create! valid_attributes
      get :show, {:id => daily_task.to_param}, valid_session
      assigns(:daily_task).should eq(daily_task)
    end
  end

  describe "GET new" do
    it "assigns a new daily_task as @daily_task" do
      get :new, {}, valid_session
      assigns(:daily_task).should be_a_new(DailyTask)
    end
  end

  describe "GET edit" do
    it "assigns the requested daily_task as @daily_task" do
      daily_task = DailyTask.create! valid_attributes
      get :edit, {:id => daily_task.to_param}, valid_session
      assigns(:daily_task).should eq(daily_task)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DailyTask" do
        expect {
          post :create, {:daily_task => valid_attributes}, valid_session
        }.to change(DailyTask, :count).by(1)
      end

      it "assigns a newly created daily_task as @daily_task" do
        post :create, {:daily_task => valid_attributes}, valid_session
        assigns(:daily_task).should be_a(DailyTask)
        assigns(:daily_task).should be_persisted
      end

      it "redirects to the created daily_task" do
        post :create, {:daily_task => valid_attributes}, valid_session
        response.should redirect_to(DailyTask.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved daily_task as @daily_task" do
        # Trigger the behavior that occurs when invalid params are submitted
        DailyTask.any_instance.stub(:save).and_return(false)
        post :create, {:daily_task => {}}, valid_session
        assigns(:daily_task).should be_a_new(DailyTask)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DailyTask.any_instance.stub(:save).and_return(false)
        post :create, {:daily_task => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested daily_task" do
        daily_task = DailyTask.create! valid_attributes
        # Assuming there are no other daily_tasks in the database, this
        # specifies that the DailyTask created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DailyTask.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => daily_task.to_param, :daily_task => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested daily_task as @daily_task" do
        daily_task = DailyTask.create! valid_attributes
        put :update, {:id => daily_task.to_param, :daily_task => valid_attributes}, valid_session
        assigns(:daily_task).should eq(daily_task)
      end

      it "redirects to the daily_task" do
        daily_task = DailyTask.create! valid_attributes
        put :update, {:id => daily_task.to_param, :daily_task => valid_attributes}, valid_session
        response.should redirect_to(daily_task)
      end
    end

    describe "with invalid params" do
      it "assigns the daily_task as @daily_task" do
        daily_task = DailyTask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DailyTask.any_instance.stub(:save).and_return(false)
        put :update, {:id => daily_task.to_param, :daily_task => {}}, valid_session
        assigns(:daily_task).should eq(daily_task)
      end

      it "re-renders the 'edit' template" do
        daily_task = DailyTask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DailyTask.any_instance.stub(:save).and_return(false)
        put :update, {:id => daily_task.to_param, :daily_task => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested daily_task" do
      daily_task = DailyTask.create! valid_attributes
      expect {
        delete :destroy, {:id => daily_task.to_param}, valid_session
      }.to change(DailyTask, :count).by(-1)
    end

    it "redirects to the daily_tasks list" do
      daily_task = DailyTask.create! valid_attributes
      delete :destroy, {:id => daily_task.to_param}, valid_session
      response.should redirect_to(daily_tasks_url)
    end
  end

end
