require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GoogleAnalyticsController do

  # This should return the minimal set of attributes required to create a valid
  # GoogleAnalytic. As you add validations to GoogleAnalytic, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GoogleAnalyticsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all google_analytics as @google_analytics" do
      google_analytic = GoogleAnalytic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:google_analytics).should eq([google_analytic])
    end
  end

  describe "GET show" do
    it "assigns the requested google_analytic as @google_analytic" do
      google_analytic = GoogleAnalytic.create! valid_attributes
      get :show, {:id => google_analytic.to_param}, valid_session
      assigns(:google_analytic).should eq(google_analytic)
    end
  end

  describe "GET new" do
    it "assigns a new google_analytic as @google_analytic" do
      get :new, {}, valid_session
      assigns(:google_analytic).should be_a_new(GoogleAnalytic)
    end
  end

  describe "GET edit" do
    it "assigns the requested google_analytic as @google_analytic" do
      google_analytic = GoogleAnalytic.create! valid_attributes
      get :edit, {:id => google_analytic.to_param}, valid_session
      assigns(:google_analytic).should eq(google_analytic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GoogleAnalytic" do
        expect {
          post :create, {:google_analytic => valid_attributes}, valid_session
        }.to change(GoogleAnalytic, :count).by(1)
      end

      it "assigns a newly created google_analytic as @google_analytic" do
        post :create, {:google_analytic => valid_attributes}, valid_session
        assigns(:google_analytic).should be_a(GoogleAnalytic)
        assigns(:google_analytic).should be_persisted
      end

      it "redirects to the created google_analytic" do
        post :create, {:google_analytic => valid_attributes}, valid_session
        response.should redirect_to(GoogleAnalytic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved google_analytic as @google_analytic" do
        # Trigger the behavior that occurs when invalid params are submitted
        GoogleAnalytic.any_instance.stub(:save).and_return(false)
        post :create, {:google_analytic => {}}, valid_session
        assigns(:google_analytic).should be_a_new(GoogleAnalytic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GoogleAnalytic.any_instance.stub(:save).and_return(false)
        post :create, {:google_analytic => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested google_analytic" do
        google_analytic = GoogleAnalytic.create! valid_attributes
        # Assuming there are no other google_analytics in the database, this
        # specifies that the GoogleAnalytic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GoogleAnalytic.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => google_analytic.to_param, :google_analytic => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested google_analytic as @google_analytic" do
        google_analytic = GoogleAnalytic.create! valid_attributes
        put :update, {:id => google_analytic.to_param, :google_analytic => valid_attributes}, valid_session
        assigns(:google_analytic).should eq(google_analytic)
      end

      it "redirects to the google_analytic" do
        google_analytic = GoogleAnalytic.create! valid_attributes
        put :update, {:id => google_analytic.to_param, :google_analytic => valid_attributes}, valid_session
        response.should redirect_to(google_analytic)
      end
    end

    describe "with invalid params" do
      it "assigns the google_analytic as @google_analytic" do
        google_analytic = GoogleAnalytic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GoogleAnalytic.any_instance.stub(:save).and_return(false)
        put :update, {:id => google_analytic.to_param, :google_analytic => {}}, valid_session
        assigns(:google_analytic).should eq(google_analytic)
      end

      it "re-renders the 'edit' template" do
        google_analytic = GoogleAnalytic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GoogleAnalytic.any_instance.stub(:save).and_return(false)
        put :update, {:id => google_analytic.to_param, :google_analytic => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested google_analytic" do
      google_analytic = GoogleAnalytic.create! valid_attributes
      expect {
        delete :destroy, {:id => google_analytic.to_param}, valid_session
      }.to change(GoogleAnalytic, :count).by(-1)
    end

    it "redirects to the google_analytics list" do
      google_analytic = GoogleAnalytic.create! valid_attributes
      delete :destroy, {:id => google_analytic.to_param}, valid_session
      response.should redirect_to(google_analytics_url)
    end
  end

end
